name: sensibilisation
description: A new Flutter project.


version: 1.0.3+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^0.5.25+3
  http: ^0.12.0+4
  beautifulsoup: ^0.0.1
  html: ^0.13.3+3
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.7+2
  flutter_local_notifications: ^1.4.1
  path_provider: ^1.6.5
  rxdart: ^0.23.1
  audioplayers: ^0.15.0
  background_fetch: '^0.5.1'
  workmanager: ^0.2.0
  provider: ^4.0.5
  #flutter_map: ^0.9.0
  webview_flutter: ^0.3.19+9
  sqflite: ^1.3.0
  intl: ^0.16.1
  lottie: ^0.3.3
  flutter_svg: ^0.17.4
  rflutter_alert: ^1.0.3
  rename: ^1.2.0
  custom_radio_grouped_button: ^1.0.0
  simple_animations: ^2.0.2
  flutter_launcher_icons: ^0.7.5
  grouped_buttons: ^1.0.4
  flutter_spinkit: ^4.1.2+1
dependency_overrides:
  intl: ^0.16.0



  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/bl.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/bg.svg
    - assets/logomove.json
    - assets/testlogo2.json
    - assets/logoloading.json
    - assets/loading.json
    - assets/doctor2.json
    - assets/doctor3.json
    - assets/testlogo4.json
    - assets/youtube.svg
    - assets/testlogo3.json
    - assets/testlogo.json
    - assets/logo.png
    - assets/charging.json
    - assets/comp1.json
    - assets/sarokh.json
    - assets/cube.json
    - assets/comp2.json
    - assets/comp4.json
    - assets/virus.json
    - assets/images/
    - assets/dark.json
    - assets/clean.jpg
    - assets/clean15.jpg
    - assets/eat.jpg
    - assets/sport.jpg
    - assets/getout.jpg
    - assets/images/markor.png
    - assets/images/q1.png
    - assets/images/q2.png
    - assets/images/q3.png
    - assets/images/fr1.png
    - assets/images/f2.png
    - assets/images/fr3.png
    - assets/images/en1.png
    - assets/images/en2.png
    - assets/images/en3.png
    - lib/lang/ar.json
    - lib/lang/fr.json
    - lib/lang/en.json
    - assets/flags/fr.png
    - assets/flags/ma.png
    - assets/flags/us.png
    - assets/flags/translate.png


  fonts:
    - family: Questv
      fonts:
        - asset: assets/fonts/QuestvRegular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/RalewayRegular.ttf
        
    - family: RalewayLight
      fonts:
        - asset: assets/fonts/RalewayLight.ttf

    - family: RalewayMedium
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
